# Generated by Django 5.2.8 on 2025-11-16 12:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("slug", models.SlugField(max_length=250, unique=True)),
                ("content", models.TextField()),
                ("excerpt", models.CharField(blank=True, max_length=500)),
                ("image", models.ImageField(blank=True, null=True, upload_to="blog/")),
                ("author", models.CharField(default="Ojasritu", max_length=100)),
                ("published", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_featured", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-published"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.ImageField(blank=True, null=True, upload_to="categories/"),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="categories/bg/"
                    ),
                ),
                ("hindi_name", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("subject", models.CharField(max_length=300)),
                ("message", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "सामान्य"),
                            ("complaint", "शिकायत"),
                            ("feedback", "प्रतिक्रिया"),
                            ("partnership", "साझेदारी"),
                        ],
                        max_length=100,
                    ),
                ),
                ("is_resolved", models.BooleanField(default=False)),
                ("admin_response", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_en", models.CharField(max_length=300)),
                ("question_hi", models.CharField(blank=True, max_length=300)),
                ("answer_en", models.TextField()),
                ("answer_hi", models.TextField(blank=True)),
                ("category", models.CharField(max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "FAQs",
                "ordering": ["order", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("hindi_title", models.CharField(blank=True, max_length=300)),
                ("slug", models.SlugField(unique=True)),
                ("content", models.TextField()),
                ("excerpt", models.TextField(max_length=500)),
                ("featured_image", models.ImageField(upload_to="articles/")),
                ("category", models.CharField(max_length=100)),
                ("views", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Articles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_date", models.DateField()),
                ("booking_time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "पेंडिंग"),
                            ("confirmed", "पुष्टि किया गया"),
                            ("completed", "पूर्ण"),
                            ("cancelled", "रद्द"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-booking_date"],
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("hindi_name", models.CharField(blank=True, max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("benefits", models.TextField(help_text="Health benefits in Hindi")),
                ("ingredients", models.TextField()),
                (
                    "usage_instructions",
                    models.TextField(blank=True, help_text="कैसे उपयोग करें"),
                ),
                (
                    "scientific_research",
                    models.TextField(blank=True, help_text="वैज्ञानिक अनुसंधान"),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "bulk_discount",
                    models.JSONField(
                        blank=True, default=dict, help_text="{'10': 10, '50': 15}"
                    ),
                ),
                ("image", models.ImageField(upload_to="products/")),
                ("gallery", models.JSONField(blank=True, default=list)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="products/thumbnails/"
                    ),
                ),
                (
                    "dosha_type",
                    models.CharField(
                        choices=[
                            ("vata", "वात"),
                            ("pitta", "पित्त"),
                            ("kapha", "कफ"),
                            ("tridosha", "त्रिदोष संतुलित"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ayurvedic_classification",
                    models.CharField(blank=True, max_length=200),
                ),
                ("quantity_in_stock", models.PositiveIntegerField(default=0)),
                ("sku", models.CharField(blank=True, max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "सक्रिय"),
                            ("inactive", "निष्क्रिय"),
                            ("discontinued", "बंद"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_bestseller", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_new", models.BooleanField(default=False)),
                ("is_organic", models.BooleanField(default=False)),
                (
                    "rating",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="shop.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "-is_bestseller", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shop.cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("comment", models.TextField()),
                ("verified_purchase", models.BooleanField(default=False)),
                ("helpful_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Rebooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consultation_type",
                    models.CharField(
                        choices=[
                            ("general", "सामान्य परामर्श"),
                            ("dosha_analysis", "दोष विश्लेषण"),
                            ("diet_plan", "आहार योजना"),
                            ("skincare", "त्वचा देखभाल"),
                            ("immunity", "प्रतिरक्षा बूस्ट"),
                            ("custom", "कस्टम चिकित्सा"),
                        ],
                        max_length=20,
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("scheduled_time", models.TimeField()),
                ("duration_minutes", models.PositiveIntegerField(default=30)),
                ("health_concerns", models.TextField(help_text="स्वास्थ्य संबंधी चिंताएं")),
                (
                    "current_medications",
                    models.TextField(blank=True, help_text="वर्तमान दवाएं (यदि कोई हो)"),
                ),
                ("allergies", models.TextField(blank=True)),
                (
                    "dosha_type",
                    models.CharField(
                        choices=[
                            ("vata", "वात"),
                            ("pitta", "पित्त"),
                            ("kapha", "कफ"),
                            ("unknown", "पता नहीं"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "अनुरोधित"),
                            ("confirmed", "पुष्टि किया गया"),
                            ("completed", "पूर्ण"),
                            ("cancelled", "रद्द किया गया"),
                            ("rescheduled", "पुनः निर्धारित"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("therapist_name", models.CharField(blank=True, max_length=200)),
                ("consultation_notes", models.TextField(blank=True)),
                (
                    "consultation_fee",
                    models.DecimalField(decimal_places=2, default=500, max_digits=10),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("payment_id", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rebookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recommended_products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="recommended_in_rebookings",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Rebookings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=100, unique=True)),
                ("shipping_address", models.TextField(blank=True, null=True)),
                ("billing_address", models.TextField(blank=True, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("final_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "लंबित"),
                            ("confirmed", "पुष्टि किया गया"),
                            ("processing", "प्रसंस्करण"),
                            ("shipped", "भेजा गया"),
                            ("delivered", "सुपुर्द किया गया"),
                            ("cancelled", "रद्द किया गया"),
                            ("refunded", "धनवापसी"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("credit_card", "क्रेडिट कार्ड"),
                            ("debit_card", "डेबिट कार्ड"),
                            ("upi", "UPI"),
                            ("wallet", "डिजिटल वॉलेट"),
                            ("cod", "नकद"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "लंबित"),
                            ("completed", "पूर्ण"),
                            ("failed", "विफल"),
                        ],
                        max_length=20,
                    ),
                ),
                ("transaction_id", models.CharField(blank=True, max_length=200)),
                ("special_instructions", models.TextField(blank=True)),
                ("admin_notes", models.TextField(blank=True)),
                ("tracking_number", models.CharField(blank=True, max_length=100)),
                ("estimated_delivery", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["order_id"], name="shop_order_order_i_6fac8b_idx"
                    ),
                    models.Index(
                        fields=["customer"], name="shop_order_custome_edf08a_idx"
                    ),
                    models.Index(
                        fields=["status"], name="shop_order_status_63c2c0_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["slug"], name="shop_produc_slug_76971b_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category"], name="shop_produc_categor_d249e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["status"], name="shop_produc_status_295d4c_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="productreview",
            unique_together={("product", "customer")},
        ),
        migrations.AddIndex(
            model_name="rebooking",
            index=models.Index(
                fields=["customer"], name="shop_rebook_custome_e8584f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rebooking",
            index=models.Index(
                fields=["scheduled_date"], name="shop_rebook_schedul_367a4e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rebooking",
            index=models.Index(fields=["status"], name="shop_rebook_status_37bdac_idx"),
        ),
    ]
