# Generated by Django 6.0 on 2025-12-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="GurukulNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Gurukul Notification",
                "verbose_name_plural": "Gurukul Notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
